### ISSUE TITLE
createServer twice and HTTPServer not working

### ISSUE THREAD

**Issue by unional** [unional/typed-http-server#1]
`createServer()` reported two definitions on vscode:
![image](https://cloud.githubusercontent.com/assets/3254987/12667891/e6dd52a4-c605-11e5-8600-7ffcd5a7fb71.png)

This happens only on js file. ts file seems to work fine.  Maybe it is a bug on vscode?
I can't verify it on atom as I don't know what package I need to get it working on atom.

`new HTTPServer()` returns `any`.
![image](https://cloud.githubusercontent.com/assets/3254987/12667957/a6ac718c-c606-11e5-8f59-4d462619d7bc.png)

@blakeembrey, how do I fix these two issues?

**Comment by blakeembrey** [comment]
Is it simple to reproduce? Not sure by "This happens only on js file" - is this TypeScript 1.8 features? I'll sure sure to review tomorrow, it's late now.

**Comment by blakeembrey** [comment]
Oh, and for the second issue, I think the definition should say `var HTTPServer: typeof HttpServer`. Give that a go?

**Comment by unional** [comment]
It's easy to reproduce.
And the repo is ready to show how it works with `import dr from 'domready'`.
Want to give it a try tomorrow?
https://github.com/coolcodeexamples/timely-wealth-game

**Comment by blakeembrey** [comment]
@unional Awesome, cheers! I see what's going on now. There's probably two definitions because of `browser/*` and `main/*`. Can you make a `jsconfig.json` file and exclude `browser`? I'm only guessing from what I've heard that this is the new feature to use type definitions on JavaScript.

Perhaps in another major version in the future, the dual output will change because of things like this. Which is a bummer, because I do actually use it myself.

**Comment by unional** [comment]
Your suggestion on the `typeof HTTPServer` works. Checking that in.

Ok. Let me try that (exclude)

**Comment by blakeembrey** [comment]
> Your suggestion on the typeof HTTPServer works.

Just an FYI, but the reason it works is because classes are effectively the value (a constructor function) and the instance type. The instance type is what we used, when we really wanted to use the constructor function type - which we can get to using `typeof value` (get type from value).

**Comment by unional** [comment]
Exclude doesn't work. And according to its description:
![image](https://cloud.githubusercontent.com/assets/3254987/12668441/57bd74a4-c60b-11e5-945e-11f68f76a1c2.png)
I can't use `exclude` while `files` is defined. In the same sense, when `files` is defined, it should only load those in the list.

Btw, this only happens to `createServer()`, not `HTTPServer` or `HttpServer`, so it may not be `exclude` related.

**Comment by unional** [comment]
> Just an FYI, but the reason it works is because classes are effectively the value (a constructor function) and the instance type. The instance type is what we used, when we really wanted to use the constructor function type - which we can get to using typeof value (get type from value).

Thanks for the clear explanation!

**Comment by blakeembrey** [comment]
> I can't use exclude while files is defined

Right, that's normal. I just didn't see a `jsconfig.json` (not `ts`) there. I've asked the TypeScript team about this too though, and will let you know what they say.

Edit: This is a guess based on the "Salsa" work I saw checked in, haven't tested myself. I'm heading offline now.

**Comment by unional** [comment]
On the other hand, your hunch is correct. It IS because of `browser` and `main`.

I forced it by just deleting `typings/browser` and `typings/browser.d.ts`, the overload is gone.
When I do `typings i` to get them back, the overload occurs again.

So should this be TypeScript (TypeScript language service) issue or vscode issue?

**Comment by unional** [comment]
I managed to get the `createServer()` working correctly.
I need to use `exclude` in `jsconfig.json`. `files` seems to be not working (have no effect).

https://github.com/coolcodeexamples/timely-wealth-game
https://github.com/coolcodeexamples/timely-wealth-game/tree/files-not-working

**Comment by unional** [comment]
Close since both issues are fixed.
